// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Complex.Config;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace My_Complex.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("My_Complex.Models.Apartamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("Piso")
                        .HasColumnType("integer");

                    b.Property<int>("Torre")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Usuario_id_usuario");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("My_Complex.Models.Rol", b =>
                {
                    b.Property<int>("Id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_rol"));

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("My_Complex.Models.Telefono", b =>
                {
                    b.Property<int>("id_telefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_telefono"));

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Usuario_id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_telefono");

                    b.HasIndex("Usuario_id_usuario");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("My_Complex.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<int?>("Apartamento_id_apartamento")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("My_Complex.Models.UsuarioRol", b =>
                {
                    b.Property<int>("Rol_id_rol")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("Rol_id_rol", "Usuario_id_usuario");

                    b.HasIndex("Usuario_id_usuario");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("My_Complex.Models.Apartamento", b =>
                {
                    b.HasOne("My_Complex.Models.Usuario", "Usuario")
                        .WithMany("Apartamentos")
                        .HasForeignKey("Usuario_id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("My_Complex.Models.Telefono", b =>
                {
                    b.HasOne("My_Complex.Models.Usuario", "Usuario")
                        .WithMany("Telefonos")
                        .HasForeignKey("Usuario_id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("My_Complex.Models.UsuarioRol", b =>
                {
                    b.HasOne("My_Complex.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("Rol_id_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My_Complex.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("Usuario_id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("My_Complex.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("My_Complex.Models.Usuario", b =>
                {
                    b.Navigation("Apartamentos");

                    b.Navigation("Telefonos");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
