// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_complex_.Config;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace My_complex_.Migrations
{
    [DbContext(typeof(VisitantesDbContext))]
    [Migration("20260527001646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("My_complex_.Models.Autoriza", b =>
                {
                    b.Property<int>("id_autorizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_autorizacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_autorizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Usuario_id")
                        .HasColumnType("integer");

                    b.Property<int>("Visitante_id_visitante")
                        .HasColumnType("integer");

                    b.HasKey("id_autorizacion");

                    b.HasIndex("Visitante_id_visitante");

                    b.ToTable("Autorizaciones");
                });

            modelBuilder.Entity("My_complex_.Models.RegistroVisita", b =>
                {
                    b.Property<int>("id_registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_registro"));

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Salida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visitante_id_visitante")
                        .HasColumnType("integer");

                    b.HasKey("id_registro");

                    b.HasIndex("Visitante_id_visitante");

                    b.ToTable("RegistroVisitas");
                });

            modelBuilder.Entity("My_complex_.Models.Visitante", b =>
                {
                    b.Property<int>("id_visitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_visitante"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Salida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_visitante");

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("My_complex_.Models.Autoriza", b =>
                {
                    b.HasOne("My_complex_.Models.Visitante", null)
                        .WithMany()
                        .HasForeignKey("Visitante_id_visitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("My_complex_.Models.RegistroVisita", b =>
                {
                    b.HasOne("My_complex_.Models.Visitante", null)
                        .WithMany()
                        .HasForeignKey("Visitante_id_visitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
